import React from "react";
import Head from "next/head";
import Navbar from "../src/components/Navbar";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const dados = [
    {
      titulo: "Fullname :",
      info: "André Lopes Melani",
    },
    {
      titulo: "Birthday : ",
      info: "25 November 1999",
    },
    {
      titulo: "Phone number : ",
      info: "(11) 94106-6927",
    },
    {
      titulo: "Email :",
      info: "andre.lopes.melani@hotmail.com",
    },
  ];

  const contact = [
    {
      url: "/images/map.svg",
      titulo: "ADDRESS",
      info: "Av. Silva Jardim, 2014 - Curitiba, PR",
    },
    {
      url: "/images/mobile.svg",
      titulo: "PHONE NUMBER",
      info: "(11) 94106-6927",
    },
    {
      url: "/images/desktop.svg",
      titulo: "WEBSITE",
      info: "www.andremelani.com.br",
    },
  ];

  const experience = [
    {
      titulo: "Company :",
      info: "ComboApps",
    },
    {
      titulo: "Period working : ",
      info: "Apr/2017 until Dez/2017",
    },
    {
      titulo: "Occupation: ",
      info: "Internship - Front-End Developer",
    },
    {
      titulo: "Description :",
      info: "Code Analysis and Web Development (HTML, CSS, PHP and MySQL).",
    },
  ];

  const experience2 = [
    {
      titulo: "Company :",
      info: "Mindtech - IoT Soluction",
    },
    {
      titulo: "Period working : ",
      info: "Jun/2021 until Dez/2021",
    },
    {
      titulo: "Occupation: ",
      info: "Internship - Front-End Developer",
    },
    {
      titulo: "Description :",
      info: "- Code analysis.",
      info2:
        "- Development and Web applications (HTML, CSS, SASS, JavaScript, React, Typescript, MongoDB, etc).",
      info3: "- Code versioning with Git, GitLab and Bitbucket.",
      info4: "- Application of Scrum methodology.",
      info5: "- Mobile development (Android and IOS) with React Native.",
      info6: "- Amazon Artificial Intelligence Skill Creation (Alexa).",
    },
  ];

  const experience3 = [
    {
      titulo: "Company :",
      info: "Meu Pet Club",
    },
    {
      titulo: "Period working : ",
      info: "Dez/2021 until May/2022",
    },
    {
      titulo: "Occupation: ",
      info: "Front-End Developer JR",
    },
    {
      titulo: "Description :",
      info: "- Code analysis.",
      info2:
        "- Development and Web applications (HTML, CSS, SASS, JavaScript, React, Typescript, MongoDB, etc).",
      info3: "- Code versioning with Git, GitLab and Bitbucket.",
      info4: "- API creation and application.",
      info5: "- Creation of own Framework.",
      info6: "- Unit testing with Jest and Enzyme.",
      info7: "- Clean code architecture.",
      info8: "- Application of Scrum methodology.",
    },
  ];

  return (
    <div className={styles.container} id="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <section>
        <div className={styles.apresentacao}>
          <div className={styles.nome}>
            <span>I am André Melani</span>
            <div className={styles.funcao}>
              Web Developer / Front-End / UX Designer
            </div>
          </div>

          <div className={styles.foto}>
            <div className={styles.areaFoto}></div>
          </div>
        </div>
      </section>

      <section id="about">
        <div className={styles.sobre}>
          <span>ABOUT ME</span>
          <p>
            My name is André Melani. I am a passionate <b>web desiger</b> and{" "}
            <b>developer</b> with five years<br></br>
            experience. I am currently studying computer engineering, but my
            passion is programming. Sport is something <br></br> very present in
            my life and I am a good cook, believe it or not! XD!
          </p>
          <div className={styles.experiencia}>
            <div className={styles.info}>
              <div className={styles.foto}>
                <img src="/images/andre.jfif" />
              </div>
              {dados.map((dado) => (
                <>
                  <div className={styles.dados}>
                    <div className={styles.pessoais}>
                      <span>{dado.titulo}</span>
                      <p>{dado.info}</p>
                    </div>
                  </div>
                </>
              ))}
            </div>
            <div className={styles.linguagem}>
              <span>SKILLS</span>
              <div className={styles.niveis}>
                <span>HTML5 &amp; CSS3</span>
                <div className={styles.full}>
                  <div className={styles.porcentagem1}>90%</div>
                </div>
              </div>
              <div className={styles.niveis}>
                <span>JAVASCRIPT</span>
                <div className={styles.full}>
                  <div className={styles.porcentagem2}>90%</div>
                </div>
              </div>
              <div className={styles.niveis}>
                <span>REACT &amp; REACT NATIVE</span>
                <div className={styles.full}>
                  <div className={styles.porcentagem3}>80%</div>
                </div>
              </div>
              <div className={styles.niveis}>
                <span>TYPESCRIPT</span>
                <div className={styles.full}>
                  <div className={styles.porcentagem4}>50%</div>
                </div>
              </div>
              <div className={styles.niveis}>
                <span>C &amp; C++</span>
                <div className={styles.full}>
                  <div className={styles.porcentagem5}>85%</div>
                </div>
              </div>
              <div className={styles.niveis}>
                <span>PYTHON</span>
                <div className={styles.full}>
                  <div className={styles.porcentagem6}>60%</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="services">
        <div className={styles.services}>
          <span>SERVICES</span>
          <div className={styles.servicesArea}>
            <div className={styles.card}>
              <img src="/images/ux.png" />
              <div className={styles.text}>
                <span>UX/UI Design</span>
                <p>
                  Design thinking about the best interaction with the user, both
                  in interface and experience
                </p>
              </div>
            </div>
            <div className={styles.card}>
              <img src="/images/developer.png" />
              <div className={styles.text}>
                <span>Developer</span>
                <p>Web development for creating websites and applications.</p>
              </div>
            </div>
            <div className={styles.card}>
              <img src="/images/communication.png" />
              <div className={styles.text}>
                <span>Communication</span>
                <p>Teamwork with Scrum methodology and great interaction.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section id="experience">
        <div className={styles.experience}>
          <span>EXPERIENCE</span>

          <div className={styles.card}>
            <div className={styles.imageArea}>
              <img
                src="https://comboapps.com.br/wp-content/uploads/2018/11/Logo-combo-apps-preto-cinza.png"
                width={300}
              />
            </div>
            <div className={styles.information}>
              {experience.map((exp) => (
                <>
                  <div className={styles.dados}>
                    <div className={styles.pessoais}>
                      <span>{exp.titulo}</span>
                      <p>{exp.info}</p>
                    </div>
                  </div>
                </>
              ))}
            </div>
          </div>

          <div className={styles.cardRight}>
            <div className={styles.imageArea}>
              <img
                src="https://mindtech.com.br/wp-content/uploads/2020/01/logo-site-1131.png"
                width={300}
                height={120}
              />
            </div>
            <div className={styles.information}>
              {experience2.map((exp2) => (
                <>
                  <div className={styles.dados}>
                    <div className={styles.pessoais}>
                      <span>{exp2.titulo}</span>
                      <p>{exp2.info}</p>
                      <p>{exp2.info2}</p>
                      <p>{exp2.info3}</p>
                      <p>{exp2.info4}</p>
                      <p>{exp2.info5}</p>
                      <p>{exp2.info6}</p>
                    </div>
                  </div>
                </>
              ))}
            </div>
          </div>

          <div className={styles.card}>
            <div className={styles.imageArea}>
              <img
                src="https://meupetclub.com.br/_next/image?url=%2F_next%2Fstatic%2Fimage%2Fpublic%2Ficons%2Fheader%2Flogo.f722c2e1843f13e863ac2885cbc00c42.svg&w=256&q=75"
                width={200}
              />
            </div>
            <div className={styles.information}>
              {experience3.map((exp3) => (
                <>
                  <div className={styles.dados}>
                    <div className={styles.pessoais}>
                      <span>{exp3.titulo}</span>
                      <p>{exp3.info}</p>
                      <p>{exp3.info2}</p>
                      <p>{exp3.info3}</p>
                      <p>{exp3.info4}</p>
                      <p>{exp3.info5}</p>
                      <p>{exp3.info6}</p>
                      <p>{exp3.info7}</p>
                      <p>{exp3.info8}</p>
                    </div>
                  </div>
                </>
              ))}
            </div>
          </div>
        </div>
      </section>
      <section id="contact">
        <div className={styles.contact}>
          <span>CONTACT</span>
          <div className={styles.contactArea}>
            {contact.map((cont) => (
              <>
                <div className={styles.card}>
                  <img src={cont.url} width={50} />
                  <div className={styles.text}>
                    <span>{cont.titulo}</span>
                    <p>{cont.info}</p>
                  </div>
                </div>
              </>
            ))}
          </div>
          <div className={styles.inputArea}>
            <input type="text" placeholder="Name*" required />
            <input type="email" placeholder="Email*" required />
            <input type="text" placeholder="Phone*" required />
          </div>
          <div className={styles.textAreaInput}>
            <textarea id="w3review" name="w3review" rows="8" placeholder="Comment*" required></textarea>
          </div>
          <div className={styles.buttonArea}>
            <button type="submit">SEND MESSAGE</button>
          </div>
        </div>
      </section>

      <section>
        <div className={styles.footer}>
          <span>www.andremelani.com.br</span>
          <span>COPYRIGHT &#169; 2022 ALL RIGHT RESERVED</span>

          <div className={styles.icon}>
            <a href="https://www.linkedin.com/in/andrelopesmelani/">
              <img src="/images/linkedin.svg" alt="Linkedin" />
            </a>
            <a href="https://www.instagram.com/melaniandre/">
              <img src="/images/instagram-alt.svg" alt="Instagram" />
            </a>
            <a href="https://www.facebook.com/profile.php?id=100014855532830">
              <img src="/images/facebook-f.svg" alt="Facebook" />
            </a>
          </div>
        </div>
      </section>
    </div>
  );
}
